### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [jdecock/harriet-beecher-stowe_uncle-toms-cabin#1]
Epigraphs:

- [x] The chapters that begin with epigraphs need to use `<header>` elements. See [SEMOS 7.4.4.1](https://standardebooks.org/manual/1.6.3/single-page#7.4.4.1) on how they should be structured.

Contractions:

- [x] There are some contractions that include spaces where there are none in the page scans: "on ’t", "you ’s", "yer ’s", etc. You can remove the spaces in these contractions ([SEMOS 8.7.4](https://standardebooks.org/manual/1.6.3/single-page#8.7.4)).

Endnotes:

- [x] In note 3, the backlink needs to be outside of the `<blockquote>` and in its own `<p>` element ([SEMOS 7.10.5.2.2](https://standardebooks.org/manual/1.6.3/single-page#7.10.5.2.2)). You can remove the `se-lint-ignore.xml` file.

Chapter 12:

- [x] There's a slightly better way of formatting the letter's `<footer>` content.
```
				<footer>
					<p>“<span epub:type="z3998:sender">Samuel Morris</span>,<br/>
					<span epub:type="z3998:sender">Thomas Flint</span>,<br/>
					<em>Executors</em>.”</p>
				</footer>
```
Tagging each name will prevent the `z3998:sender` semantic from changing the font for "Executors".

Chapter 28:

- [x] The songs are missing language tags.

Chapter 35:

- [x] Childe Harold’s Pilgrimage is a poem. It needs to be in quotes.

- [x] Remove the period after the citation.

Chapter 43:

- [x] The postscript needs to be inside of a `<blockquote epub:type="z3998:letter">`.

content.opf:

- [x] The subject "Drama" is for plays. A better subject would be "Fiction".

local.css:

- [x] You'll need to add the CSS for epigraphs in section headers ([SEMOS 7.4.4.2](https://standardebooks.org/manual/1.6.3/single-page#7.4.4.2)).

- [x] Adjust your styling for the `<footer>`s to be:
```
footer{
	margin-top: 1em;
	text-align: right;
}
```

- [x] You're missing the CSS for the `z3998:sender` semantic.

- [x] You can remove:
```
footer em{
	font-variant: initial;
}
```
